### ISSUE TITLE
Forum Rep Points

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#109]
1) rank users by forum reputation (0-99) 

2) Figure out "A" (activity)
It's the number of active users (someone that posted, commented, or voted on the forum on that quarter moon cycle)

3) 
Rep points to distribute on that quarter cycle == 1/10th of A (1/10th is a setting on Constitution)
Distribute according to rank: 99th receives 99 times more

Example:
This quarter, 100 users were active (of a total of 1000 ranked users) on the Forum
A = 100, we are distributing 100

Rank 99 users will get 99 x 10 / TOTAL = 1
Rank 98 users will get 98 x 10 / TOTAL = 1
Rank 97 users will get 97 x 10 / TOTAL = 1
Rank 96 users will get 96 x 10 / TOTAL = 1
Rank 95 users will get 95 x 10 / TOTAL = 1
Rank 94 users will get 94 x 10 / TOTAL = 1
Rank 93 users will get 93 x 10 / TOTAL = 1
Rank 92 users will get 92 x 10 / TOTAL = 1
Rank 91 users will get 91 x 10 / TOTAL = 1
Rank 90 users will get 90 x 10 / TOTAL = 1
Rank 89 users will get 89 x 10 / TOTAL = 0 (rounded down)

...

SUM(1+2+3...+98+99) x 10 / SUM

## Step 1: Figure out forum rep points with voting etc
 - I think we have that already

## Step 2: Rank forum rep points with ranking algorithm 99-0 as usual
- Normal ranking

## Step 3: Every 1/4 moon cycle, distribute reputation points based on forum rep points, number of people playing

- rep points available == number of people active over same period
- period rep points = # number of ranked people
- 1/10th of that number
- rep points are integers

## Data Required
- Number of active users in period - keep size in size table
- Points of each active user
- Rank of each active user

## Deployment
- [ ]  forum contract
- [ ]   settings contract
- [ ]   scheduler contract
- [ ]   reset settings
- [ ]   reset scheduler ? -< don't do that, add new things manually, no reset, it WILL screw up existing ops!
- [ ]   updatePermissions

**Comment by n13** [comment]
## Step 1: Figure out forum rep points with voting etc - I think we have that already

## Step 2: Rank forum rep points with ranking algorithm 99-0 as usual

## Step 3: Every 1/4 moon cycle, distribute reputation points based on forum rep points, number of people playing

// rep points available == number of people active over same period
// period rep points = # number of ranked people
// 1/10th of that number
// rep points are integers

## Data Required
- Number of active users in period
- Points of each active user
- Rank of each active user

**Comment by IanMendozaJaimes** [comment]
Hello I have a question about the implementation of the active users, I think there are two ways to check if someone is active. 
- The first one is to create an `active` table and check if an user is there, and then when distributing points delete this table's entries.
- The second one is to have a singleton to store the last time the points distribution has been run, and based on that check if the user is active during this running 1/4 of moon cycle

which one should I use?

**Comment by juliolrmonteiro** [comment]
Well, from the definition of "active", it says someone that posted, commented, or voted on the forum on that quarter moon cycle. So, can you check on the **postcomment_table** and **vote_table** during that cycle period, and get a unique list of all accounts mentioned on _author_name_account_ or _account_ fields?

Regarding the rounding for distribution, we're talking about:

With A =1000, we're distributing 100 points among the most ranked users (one user per percentile):
TOTAL = n(n+1)/2 for n=99 ranks, we have 4851 bits

Rank 99 gets:
99*100 / 4851 = 2.0408... rounds to 2

Rank 98 gets:
98*100 / 4851 = 2.0202... rounds to 2
.....
Rank 50 gets:
50*100 / 4851 = 1.0307... rounds to 1
.....
Rank 10 gets
10*100 / 4851 = 0.2061... rounds to 0

Does that make sense?

**Comment by n13** [comment]
Lets start with a higher number 100% and make a depreciation curve that starts in november and makes this number 1/2 every 90 days.
This needs to be built in from the start so that we don't have to wait on this.

**Comment by juliolrmonteiro** [comment]
Algorithm for points decay based on the amount of active users:

If we have < 1000 active users: 100% active points distributed
If we have < 10000 : 50% points
If we have between 10000 and 100.000: 20% points
if we have above 100.000: 10% points

**Comment by n13** [comment]
```
DEPLOY LOG Issue #109

/scripts/seeds.js run forum settings scheduler

./scripts/seeds.js updatePermissions

/scripts/seeds.js test forum settings scheduler

EOSIO_NETWORK=telosTestnet ./scripts/seeds.js deploy forum settings scheduler

EOSIO_NETWORK=telosTestnet ./scripts/seeds.js updatePermissions

❯ cleosm get account tlosto.seeds
created: 2019-12-19T19:33:23.500
permissions: 
     owner     1:    1 EOS6kp3dm9Ug5D3LddB8kCMqmHg2gxKpmRvTNJ6bDFPiop93sGyLR
        active     1:    1 EOS6kp3dm9Ug5D3LddB8kCMqmHg2gxKpmRvTNJ6bDFPiop93sGyLR, 1 tlosto.seeds@eosio.code
           execute     1:    1 EOS6H8Xd2iKMa3KEF4JAQLbHAxkQcyrYgWXjrRJMsY5yEr2Ws7DCj, 1 cycle.seeds@active
           purchase     1:    1 EOS75DmTxcnpvhjNekfKQzLrfwo44muPN6YPPX49vYPot4Qmo5cTo

cleos -u "https://test.hypha.earth" push action settgs.seeds reset "{}" -p settgs.seeds@active

cleos -u "https://test.hypha.earth" push action cycle.seeds reset "{}" -p cycle.seeds@active

cleos -u "https://test.hypha.earth" push action cycle.seeds start "{}" -p cycle.seeds@active


# NOTE: these run at moon cycles / 4 --> 637200 seconds
# Start time: Oct 16 2020 new moon -> 1602876660 unix timestamp

1603513860


EOSIO_NETWORK=telosMainnet ./scripts/seeds.js deploy forum settings scheduler

EOSIO_NETWORK=telosMainnet ./scripts/seeds.js updatePermissions

cleos -u "https://node.hypha.earth" push action settgs.seeds reset "{}" -p settgs.seeds@active


cleos -u "https://node.hypha.earth" push action cycle.seeds configop '{ 
	"id":"forum.rank",
	"action":"rankforums",
	"contract":"forum.seeds",
	"period":"637200",
	"starttime":"1603513860"
}' -p cycle.seeds@active

cleos -u "https://node.hypha.earth" push action cycle.seeds configop '{ 
	"id":"forum.giverp",
	"action":"givereps",
	"contract":"forum.seeds",
	"period":"637200",
	"starttime":"1603513860"
}' -p cycle.seeds@active




```

**Comment by n13** [comment]
Deployed

**Comment by n13** [comment]
I am not sure the algorithm is correct because it depends on how many people we have in total - so it's not 1 user 1 bucket

Our buckets are 0 - 99, there's 100 buckets

Inside of 1 bucket, people split equally

Meaning

If AB = amount for my bucket, then each member of the buckets gets AB/NB points. NB is the number of people in this bucket right now.

How we distribute the number per bucket is 100 buckets, the 99 gets 99x  the 1 bucket.
