### ISSUE TITLE
Proposals Changes - Flexible Quorum

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#129]
Yup! Copied above.
.90 / # of proposals = quorum required.

Min 7% max 20%
Just for now and see how this goes...

**Comment by IanMendozaJaimes** [comment]
Hello, I have question:
Does any of these parameters have to be a setting?

**Comment by n13** [comment]
Quorum is very different overall actually

We take the total number voted FOR and compare it with the number of votes for a specific proposal. 

![image](https://user-images.githubusercontent.com/65412/97449148-a9ee7100-1931-11eb-88ca-377c43659b03.jpeg)

**Comment by n13** [comment]
Use total number of votes not just positive votes
