### ISSUE TITLE
Proposals Changes - Different Stakes for Alliances and Campaigns

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#130]
Campaigns: 2.5% stake with 75,000 cap

Alliances: 1% stake and 15,000 cap.

## Implementation - 

Alliance and campaigns use the same stake caps at the moment
This will change it so they use different stake caps - need to introduce 2 new settings for this

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
- The 2.5% and 1% are based on the percentage of Seeds required, right?
- Is the 75,000/15,000 cap the maximum amount of Seeds an alliance/campaign proposal can stake?
- Just to make sure, the percentages aren't settings as well, right?
