### ISSUE TITLE
Separate voice distributions for Alliance vs Campaign type proposals

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#137]
scope voice

leave main contract scope for campaign

make new scope for alliance

distinguish proposals

helper function
name get_type(proposal->fund) -> returns prop type as it is currently determined by prop type

On a vote, determine which pool it comes out of by type

on vote distribution, distribute to both pools

**Comment by IanMendozaJaimes** [comment]
Hello I have some questions:
> name get_type(proposal->fund) -> returns prop type as it is currently determined by prop type,
- What is the prop type?, currently I think it is determined by the type of fund, but there is no attribute called prop type, what would be the difference?
- Currently I think the banks are normal accounts, and I couldn't find a way to distinguish that some user is a bank, well other than the hardcoded name, is it planned to have several bank accounts of each type?, if so, is there a table to identify the banks and their types?
> On a vote, determine which pool it comes out of by type
- Sorry, but I think I don't understand what you mean by pool. The vote table is currently scoped by proposal id, but if the proposal scope changes, then different proposals may have the same id. Is this what you mean?, What could be a good solution to that problem?, is it fine to separate the 64 bits id in two? I mean one part for the prop type and the other the proposal id? these could help, but it could be a migration problem if there are proposals already.

**Comment by n13** [comment]
> Hello I have some questions:
> 
> > name get_type(proposal->fund) -> returns prop type as it is currently determined by prop type,
> 
> * What is the prop type?, currently I think it is determined by the type of fund, but there is no attribute called prop type, what would be the difference?

Yeah we currently decide by the fund selected. 

That's why I was sugesting the helper method - a bit over-specified - do it any way you see fit please ;) 

> * Currently I think the banks are normal accounts, and I couldn't find a way to distinguish that some user is a bank, well other than the hardcoded name, is it planned to have several bank accounts of each type?, if so, is there a table to identify the banks and their types?

We use the hard-coded banks for the time being, until we need more flexibility

Eventually all these hard coded banks will be drained and the proposals will come out of the available harvest in this cycle - then this will have to be revisited. 

It would be nicer to specify them for example as settings, so we can change them but realistically they will not change until we hit go live. They're not a long term thing anyway. 

> 
> > On a vote, determine which pool it comes out of by type
> 
> * Sorry, but I think I don't understand what you mean by pool. The vote table is currently scoped by proposal id, but if the proposal scope changes, then different proposals may have the same id. Is this what you mean?, What could be a good solution to that problem?, is it fine to separate the 64 bits id in two? I mean one part for the prop type and the other the proposal id? these could help, but it could be a migration problem if there are proposals already.

I had not considered that, good point.

What I meant wasn't the vote table - it was the voice table. So we can have one voice table for each type, the contract scope for the campaigh type and a separate one "alliance"_n for the alliance type. 

So this is where the votes come from. That means for example if I have 83 voice as per my contribution score, I get 83 in the campaign type (contract scope) and 83 in the alliance scope. 

For the vote table you're right I didn't think about this. I guess the easiest thing to do would be to have a unique ID across both tables - not sure about the most elegant way to do that. Maybe a random number we can check for collision on both tables (unlikely). Or a separate counter singleton that just counts up on either type of proposal. Or...

**Comment by n13** [comment]
Done
