### ISSUE TITLE
Harvest Calculate Monthly QEV

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#139]
## Spec

Keep a table updated every 24h with 
- QEV (running over the trailing 29.5 days)
- circulating supply
- planted
- burned (?? not sure that's feasible - we don't keep track of that so far?)

## Questions
- Think through whether storing circulating supply is sufficient
- define what circulating supply is
- store extra data if we need to (burned?)

## Implementation

- Calculation - crawls tx history set up in #138 
- Store in table

- [ ] Calculate monthly QEV function with scheduler. Calc every 24h. Store circulating supply and planted and burned as well. Goes back 150 days

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
- By using the 3 tables mentioned in issue 138 would be possible to track the circulating supply, planted seeds and burned, right?
- Could you spec a bit more about what the  circulating supply is?
- I think I don't understand what you mean by "Goes back 150 days"
- Just to make sure I understood, this table will be updated daily, and the data to take into account is the data between the current day and  29.5 days ago
- Is it convenient to create a new entry in this table each cycle? I think this will be needed in the issue 140

**Comment by juliolrmonteiro** [comment]
The circulating supply is already there (updatecirc, on token.cpp)

**Comment by juliolrmonteiro** [comment]
We should keep the last 150 snapshots of the circulating supply in a table

**Comment by juliolrmonteiro** [comment]
Just to make sure I understood, this table will be updated daily, and the data to take into account is the data between the current day and 29.5 days ago ---> Yes

**Comment by juliolrmonteiro** [comment]
Store daily calculations on a table, and consider only 2 qualifying transactions(between 2 unique accounts, limit to 1777) per day. From that the monthly QEV can be calculated naturally
