### ISSUE TITLE
Cancel proposals before they become active

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#14]
- Add cancel action to proposals
- Authorized by creator
- Takes proposal ID as parameter
- Fails if the proposal is not in "open" state, ie if it's active already it can no longer be cancelled
- Return funds to creator - either directly in the cancel action, or by way of a "refund" action where they can get their Seeds back. Separate refund action is probably better.

Use case: Changed my mind about the proposal

**Comment by IanMendozaJaimes** [comment]
Hello, I have a question: 

By funds, do you mean the proposal staked value? if yes, it confuses me because in the code anyone can stake some assets to a proposal, and if the proposal is cancelled then the creator will gain the staked assets no matter who staked the assets.

**Comment by n13** [comment]
Ok let me get back to you

**Comment by n13** [comment]
@IanMendozaJaimes ok have not heard from Rieki but I think we just limit sponsors to be the owner, that way they can cancel and get the money back

**Comment by n13** [comment]
Implemented
