### ISSUE TITLE
Calculate hourly mint quantity

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#140]
Calculate daily QEV growth and outgoing hourly harvest

## Spec

Take the tables calculated in #139  with the daily values, use them to calculate how many seeds we need to grow

- Compare volume today with volume 1 quarter ago
- This is the increase in QEV - QEV growth
- Take circulating supply back then, grow it by QEV growth -> Target supply
- Calculate target  - Current circ supply  -> delta 
- spread delta over (29.5 * 24) hours = 708 hours, divide -> number to distribute each hour going forward
- Store this number - mint rate
- Refresh the number 24h later

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
- By the volume from 1 quarter ago, do you mean literally just consider the volumes from the months 3,6,9 and 12, or consider the volume three months ago, for instance if the current month is 4 (April), the previous QEV would be the QEV from month 1 (January)?
- Where should I store the QEV growth and the mint rate in a new table?
- Is QEV growth = current_QEV - previous_QEV ? that means QEV growth is measured in SEEDS right?
- mint rate = delta / 708,  right?

**Comment by juliolrmonteiro** [comment]
By the volume from 1 quarter ago, do you mean literally just consider the volumes from the months 3,6,9 and 12, or consider the volume three months ago, for instance if the current month is 4 (April), the previous QEV would be the QEV from month 1 (January)? --> Second one, rolling average QEV

**Comment by juliolrmonteiro** [comment]
Where should I store the QEV growth and the mint rate in a new table?
--> harvest contract can have a new table to store this variation of the QEV and mint rate

**Comment by juliolrmonteiro** [comment]
Is QEV growth = current_QEV - previous_QEV ? that means QEV growth is measured in SEEDS right?
--> It's a percentage growth

**Comment by juliolrmonteiro** [comment]
Refer to https://docs.google.com/document/d/1C4w9Ol8VGabCIcQDVPDrwcTRoJXBqhrb7VjslwQbUGU/edit# page 93

**Comment by juliolrmonteiro** [comment]
The minting should happen hourly, based on the daily calculation of delta QEV
