### ISSUE TITLE
Distribute test harvest

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#141]
Distribute test harvest every hour = this should get invoked from #140 once we know the rate...

Distritbute into the correct buckets with the correct amounts

**Comment by juliolrmonteiro** [comment]
Distribute another TEST SEEDS token instead, not actual SEEDS yet, token contract using "test.seeds"

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
- In the documentation says that one part of the harvest belongs to Global G-DHO Harvest, can you please tell me who is this account?
- Just to make sure I understood: 
  Let's say the `mint rate` is 1000 Seeds/hour and the distributions are like in the constitution: Residents/Citizens(30%), Bioregions(30%), Orgs(20%), Global(20%).
  
  Then 1000 Seeds have to be issued per hour, and each bucket will receive hourly:
  - Residents/Citizens => 300 Seeds
  - Bioregions => 300 Seeds
  - Orgs => 200 Seeds
  - Global => 200 Seeds
  
  Now, let's suppose there are 150 residents/citizens in total, but only 2 have a rank 99, so first I need to determine how much Seeds each rank deserves, using:
  99x + 98x + 97x + ... + 1x = 150
  In this example x = 0.0303, so the rank 99 deserves 99 * 0.0303 = 2.9997 Seeds. As there are 2 users in the rank 99, then each user receives 2.9997 / 2 = 1.4998 Seeds
  
  And the same logic applies for orgs and bioregions
  
  Is all the above right?

**Comment by n13** [comment]
On 1 - G-DHO is the harvest contract... this pool will be used to find proposals.

**Comment by IanMendozaJaimes** [comment]
Hello @n13, I have some other questions:

- Is contribution score for orgs been calculated in the action `calccss`?, If so, I think it is missing the transaction score for orgs, is it ok to change it in this ticket?

- I have noticed that the contribution score for bioregions is not being calculated, for the moment, what should I do with the part of the harvest belonging to bioregions?

> Seeds each rank deserves, using:
99x + 98x + 97x + ... + 1x = 300 Seeds
In this example x = 0.0606, so the rank 99 deserves 99 * 0.0606 = 5.9994 Seeds. As there are 2 users in the rank 99, then each user receives 5.9994 / 2 = 2.9997 Seeds
- There is kind of a problem with this approach, I didn't notice that if there aren't enough users to have at least one in each rank, the amount of Seeds reserved for that rank will be unused. For example, if there are no users with rank 33, then the 33 * 0.0606 = 1.9998 Seeds for all users in that rank won't be assigned to anyone. In this moment, the unused Seeds would be stored in Global, but I don't know if this is correct. The same thing would happen for orgs and bioregions.

- Is it ok to name the test token as THSEEDS? (stands for Test Harvest Seeds)

- To issue THSEEDS (and eventually SEEDS), it is needed the owner's authority, but the owner is different depending on the net the contracts are running. Is there any problem if I use the contracts table from settings to store the owner? the problem with this is that depending on the net the owner should be changed with the action `setcontract`

**Comment by n13** [comment]
Can you call them TESTS - for test Seeds ;) 

Would rather not have them use the term SEEDS in them ;) 

Org score - yes tx score add if missing

Bioregions - as long as we don't do CS for them, let each BR have a CS of 1 - so we can distribute something

I believe that BR scores are going to be based on the scores of the members but I have to figure this out - finding these holes is exactly why we want to be distributing test seeds right now - perfect. @Rieki7 

For issuance - we need to add "mint" rights to the contract doing the calculations - this is true for Seeds too, harvest needs to be able to mint new tokens. 

We need to secure this properly I will think about that. But for the time being, we can add a minttest action to Token, and make sure it is restricted to always only mint TESTS, can't mint Seeds. 

Then we add a permission so harvst.seeds can call into minttest and mint new tokens. 

For real Seeds we need to think about how to secure this properly.
