### ISSUE TITLE
Const - add vis.plant setting as min planted for invitations

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#150]
This is currently hard-coded - at 5.

Spec: Make it a setting.

**Comment by juliolrmonteiro** [comment]
Should it be named "vis.plant" or "fee.invitation", because it's not used only by visitors, right?

**Comment by juliolrmonteiro** [comment]
What about "invitation.planted"

**Comment by juliolrmonteiro** [comment]
Check if `sow_quanted` is above the minimum in `_invite`.
Make sure people ar not allowed to unplant this min quantity?
