### ISSUE TITLE
Change CBP rewards for referrals to vouching!

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#151]
## Spec

VOUCHING - gets community building points

Referrals - gets reputation points

This is currently wrong where CBP is only given for referrals

Change the names of these settings also

  // community buiding points for referrer when user becomes resident
  confwithdesc(name("vou.cbp1.ind"), 1, "Community buiding points for referrer when user becomes resident", high_impact);

  // community buiding points for referrer when user becomes citizen
  confwithdesc(name("vou.cbp2.ind"), 1, "Community buiding points for referrer when user becomes citizen", high_impact);

## Current State
- irg gets cbp when org is a referrer - orgs don't vouch so this makes sense
- org does not get rep points for this - that's pribably also OK - do orgs even get normal rep points, or only regen points as voted by citizens?
- individuals get rep points and cbp - this should change so all vouchers get cbp - we already iterate over vouch in vouchreward, so we can just add that there. 
- currently orgs also get entries in the cbp table in accounts - they should not be in there at all. 
 

## Migration
Assign CBP points for vouches for residents and citizen

Give these CBP to all vouchers, except for the referrer

Reasoning: A referrer is always also a voucher - meaning who referred me, also vouched for me

The referrer already received their CBP points reward in the old method, so they are OK - this is correct

Only the other vouchers did not receive any, so for those we play catch up

For a citizen, they get resident reward and citizen reward. For resident, they only get resident reward.

**Comment by juliolrmonteiro** [comment]
Doing the Migration for historical vouching is a bonus :)

**Comment by juliolrmonteiro** [comment]
Hey @n13, I was reviewing the constitution at https://docs.google.com/document/d/1C4w9Ol8VGabCIcQDVPDrwcTRoJXBqhrb7VjslwQbUGU/edit#

And from what I understood from the text you only get CPB when someone you invited (referral) becomes resident or citizen, not when you VOUCH for them (page 46), did this change somewhere?

From what I get at the Constituion, the current code is correct as it issues CBP only on `accounts::refreward` when the referred user becomes resident or citizen.

Can you please doublecheck if this change is needed?

**Comment by n13** [comment]
Yeah this issue was about that all who have vouched should receive this reward

Not just the referrer as it’s currently implemented
