### ISSUE TITLE
Separate org CS score from normal accounts CS score

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#160]
Harvest contract a contribution score (CS) table

Currently this table contains CS for organizations as well as accounts

Make it so it only contains CS for individuals

Organizations need their own CS table - could be scope

**Comment by n13** [comment]
We might need to separate out all org tables from individual tables

See harvest contract here on this method
void harvest::ranktx(uint64_t start_val, uint64_t chunk, uint64_t chunksize, name table) {

**Comment by juliolrmonteiro** [comment]
This seems to be done already, CS seems to be calculate at:
```C++
void harvest::calccs(uint64_t start_val, uint64_t chunk, uint64_t chunksize) {
  require_auth(_self);

  check(chunksize > 0, "chunk size must be > 0");

  uint64_t total = utils::get_users_size();
  auto uitr = start_val == 0 ? users.begin() : users.lower_bound(start_val);
  uint64_t count = 0;

  while (uitr != users.end() && count < chunksize) {
    calc_contribution_score(uitr->account);
    count++;
    uitr++;
  }
```

So it seems it only iterates over users, not over orgs.

**Comment by juliolrmonteiro** [comment]
This seems to be already done:

```C++
ACTION harvest::setorgtxpt(name organization, uint64_t tx_points) {
  require_auth(get_self());

  tx_points_tables orgtxpoints(get_self(), "org"_n.value);
```
The table is scoped differently here.

**Comment by n13** [comment]
Done
