### ISSUE TITLE
Adjust referral rewards based on formula

### ISSUE THREAD

**Issue by juliolrmonteiro** [JoinSEEDS/seeds-smart-contracts#174]
# Current system

Referral rewards calculated based on current SEEDS price on seeds.exchange contract.

# New system

Use the formula proposed on the attached spreadsheet to calculate rewards based on the current number of residents and citizens.

**Comment by juliolrmonteiro** [comment]
[AmbassadorRewards.xlsx](https://github.com/JoinSEEDS/seeds-smart-contracts/files/5605874/AmbassadorRewards.xlsx)

**Comment by juliolrmonteiro** [comment]
I am trying to create these constants that Mark proposed on `seeds.seettings` , however the settings have to be integers, right? Should I multiply them by, say 10000, too on the settings and divide on the code?

Currently I was envisioning adding the following settings to make the formula compatible to what Mark proposed:
``` 
confwithdesc(name("refrwd1.degr"), 550 , "Referrer reward degradation constant for residents", high_impact); // was 0.055
confwithdesc(name("refrwd2.degr"), 850 , "Referrer reward degradation constant for citizens", high_impact); // was 0.085
confwithdesc(name("refrwd1.min"), 20, "Minimum referrer reward for residents", high_impact);
confwithdesc(name("refrwd2.min"), 30, "Minimum referrer reward for citizens", high_impact);
confwithdesc(name("refrwd1.tot"), 2000000, "Total residents rewarded", high_impact);
confwithdesc(name("refrwd2.tot"), 1000000, "Total citizens rewarded", high_impact);
``` 

Also if I am using solely the spreadsheet provided by Mark, I am not sure how this should affects Organization rewards. Also the current code affects all rewards equally, based on price, so having different curves for different types of reward will make the code more complex.

A **simplification** that would still meets Mark's goals, IMHO, would be to just add a single degradation constant (say 0.055) that degrades all rewards exponentially with that formula, having a general purpose minimum (say 10 SEEDS), and having a general **total rewarded users** (that takes the current user count, no matter if they are citizens or residents.

What do you think of this simplification, is it doable? @n13

**Comment by markflowfarm** [comment]
NOTE: I adjusted the constants in my spreadsheet a little to make the refer.seeds pool last a little longer.  See new spreadsheet attached below if you want to look at the details.

For implementation, and ease of describing (in a chart) to the community, I believe we should use 3 constants for each of the two types of rewards.  These would be:

InitialReward:  (750 for Resident, and 1250 for Citizen)
MinimumReward: (20 for Resident, and 30 for Citizen)
DecayDenominator: (110,000 for Resident, and 75,000 for Citizen)

The reward is computed as follows (CurrentCounter is either current #Resident or current #Citizen):

Reward = MinimumReward + (InitialReward - MinimumReward) * exp( -CurrentCounter / DecayDenominator )

For Organization Rewards, I suggest the following.  Compute the reward per above, then give 80% of that number of Seeds to the Organization that sent the Invite, and 20% to the Ambassador that created the Organization.
[AmbassadorRewards_v2.xlsx](https://github.com/JoinSEEDS/seeds-smart-contracts/files/5609975/AmbassadorRewards_v2.xlsx)

**Comment by markflowfarm** [comment]
[AmbassadorRewards_v3.xlsx](https://github.com/JoinSEEDS/seeds-smart-contracts/files/5609986/AmbassadorRewards_v3.xlsx)

**Comment by markflowfarm** [comment]
![image](https://user-images.githubusercontent.com/73915187/100492645-368c7a80-30fc-11eb-9bea-9451461884fc.png)

**Comment by markflowfarm** [comment]
![image](https://user-images.githubusercontent.com/73915187/100492653-4906b400-30fc-11eb-85c6-6aa439b37342.png)

**Comment by n13** [comment]
Love it... @markflowfarm is the 80/20 split for ambassadors and orgs the same as before? I think that ratio needs to stay the same.

**Comment by markflowfarm** [comment]
It was 80/20 split of the rewards to the Org and the Ambassador in the previous (when looking combined at Resident + Citizen reward), but strangely the breakdown was a little inconsistent between the Resident and the Citizen.

![image](https://user-images.githubusercontent.com/73915187/100492925-96d0eb80-30ff-11eb-8570-05dde98be15e.png)

**Comment by markflowfarm** [comment]
NOTE:  Remember, the CurrentCounter for #Resident needs to be the total number of all "makeresident" events since inception (some of whom have further evolved to Citizen).  Is this counter being maintained in accts.seeds?

**Comment by juliolrmonteiro** [comment]
Hey there, @markflowfarm, yes that info is securely stored in the `histry.seeds` contract, inside the citizen and resident tables.

**Comment by markflowfarm** [comment]
I don't know what is stored in these two tables.  For instance, there are only 69 Citizens listed and 134 Residents.  So, this isn't right.  And.., I am in both tables, while Rieki is only in the Citizen table (not the Resident).  What am I not understanding?

**Comment by juliolrmonteiro** [comment]
> I don't know what is stored in these two tables. For instance, there are only 69 Citizens listed and 134 Residents. So, this isn't right. And.., I am in both tables, while Rieki is only in the Citizen table (not the Resident). What am I not understanding?

If I recall correctly, some genesis users are converted directly to citizens without ever being residents (maybe Rieki fits in this case?) @n13 can you help with this?
