### ISSUE TITLE
Proposals: Evaluation Phase

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#18]
# Specification

## Evaluation Phase

- After a proposal is approved, it can be voted down by all those who voted for it - that is every yes vote can change into a no vote during the evaluation phase
- Partial payouts: In the first cycle, 10% of total is paid out. Over the total number of cycles the proposal is running, each cycle a number of additional funds is paid out. Either in a linear or in a stepping up fashion. 
- Minimum run time is 3 cycles
- Default payout is 10% (initial), 30% (end of cycle 1), 30% (end of cycle 2), 30% (end of cycle 3)
 
### Stepped payout

We could also use a stepping function where each cycle the number paid out increases, i.e.

1. 10%
2. 20%
3. 30%
4. 40%

### New state: evalulate
Instead of "passed" / "closed", proposal goes into "evalulate" state

### onperiod changes
In onperiod, we check all eval state proposals
- if the votes changed, it is closed down
- if the votes didn't change (still passing) we pay out the next chunk

### Data changes and create action changes

In the creation of a proposal, and the props table, there's additional parameters
- Initial payout (default 10%, can't be higher than 20%)
- number of cycles (minimum 3)
- props table: add "cycle this proposal was passed" so we know which cycle we are in, compared to total cycle, which we're already counting.
- Alternatively, add "age" and increase age every time on onperiod, until it reached number of cycles. Age seems more intuitive and less error prone here. 

Add a function that calculates the number of Seeds to pay out in a given cycle, given the following parameters:
total cycle, cycle proposal was passed, total number of seeds requested

**Comment by juliolrmonteiro** [comment]
Discussion today with Nik:
- Move the proposal data structure to a JSON-like(map<string><Any>) data prop.
- We need to validate the schema for the map, based on the version (Json schema like validation)
- This will allow the evolution of Proposals, to evolve using Roles etc.

**Comment by IanMendozaJaimes** [comment]
Hello I have some questions:
- If a user voted no, then that user can't change their vote later on in the next proposal's cycles, right?
- Is there an upper limit on the number of cycles a proposal can run?


>Either in a linear or in a stepping up fashion
- Does this have to be chosen when the proposal is created?


>Instead of "passed" / "closed", proposal goes into "evalulate" state
 - Just to make sure I understood, if a proposal passes, then it goes to evaluate state and the initial payout is given, but if the proposal didn't pass, then it does not enter in the evaluation phase, it simply gets rejected. Then in the next cycles the proposal can still get rejected if their votes changed.

**Comment by juliolrmonteiro** [comment]
If a user voted "no", then that user can't change their vote to a "yes" later on in the next cycles, a user can only change their vote if it was a "yes" initially, right? --> Yes

**Comment by juliolrmonteiro** [comment]
Also, users that didn't vote, they can't vote in the future cycles for the already passed proposal, right? --> Yes

**Comment by juliolrmonteiro** [comment]
When a user changes their vote, the first favour points the user granted are removed and replaced by the new against points? or the favour points remain the same and just count the against points as a new vote? --> Just reverse the sign: positive votes become negative votes

**Comment by juliolrmonteiro** [comment]
Is there an upper limit on the number of cycles a proposal can run? --> 1 year (24 cycles)

**Comment by juliolrmonteiro** [comment]
Should the staked amount and the reputation be refunded as soon as the proposal gets in the evaluation phase? --> Yes

**Comment by juliolrmonteiro** [comment]
Can the initial payout be smaller than 10%? --> Yes

**Comment by juliolrmonteiro** [comment]
Is it a good idea to store the amount of Seeds already given to a proposal? I mean, in the proposal table --> Yes

**Comment by juliolrmonteiro** [comment]
When a proposal is an alliance type, it sends the requested amount to the escrow locks, if the amount is sent in different payments, then a user (or the recipient) will have several escrow lock entries, is that a problem? --> Maybe Alliance types  work different, will talk to Rieki

**Comment by juliolrmonteiro** [comment]
In the example of the stepped function: --> We will use a default distribution, will be decided with Rieki

**Comment by juliolrmonteiro** [comment]
Does this have to be chosen when the proposal is created? --> It can be edited until the proposal is live

**Comment by juliolrmonteiro** [comment]
Just to make sure I understood:
1- The proposal is created, and its creator has to stake the required amount during the cycle the proposal was created
2- Then, in onperiod the staged proposal changes to active if it has enough stake, now users can vote
3- Then, then next cycle, in onperiod the active proposal is checked, if it passes, then it goes to the evaluate state and the initial payout is given, here the age counter starts in 0. If the proposal didn't pass, then it does not enter in the evaluation phase, it simply gets rejected.
4- Then in the next cycles the proposal can be rejected if their votes changed.
5- If the proposal wasn't rejected, at the end of its cycles, then it gets into the close state

--> Yes, this is correct, add an index to find the ones by status
