### ISSUE TITLE
Settings with floating point values

### ISSUE THREAD

**Issue by juliolrmonteiro** [JoinSEEDS/seeds-smart-contracts#182]
Enable having settings with floating point values, then add a migration method if needed.

Branch here 9fe4134

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:

- When you say enabling to have a floating point value, do you mean to add another field to the config table? or replace the type uint64_t to double instead?, I think it's easier just to replace the type, also it would have less impact on the contracts, however all contracts may need to be recompiled with both options

**Comment by n13** [comment]
If you look at my branch I added a double and a boolean is_float I think

I am a bit wary of just replacing integers with doubles - there may be unexpected side effects from that, so in the interest of not having random bugs show up all over the code base, I want to keep the int values as they are. Some values are too big for doubles too I think - some of the x10,000 values. 

So overall, I am convinced that having both optins is better.

Now what we could do is add a second table with only float numbers. That's cleaner and requires less migration too. It's just harder to look up on the client side. But might be a better solution than having a table with both fields where only 1 field is ever used. 

Come to think of it, that would be easiest. No migration necessary. 

Happy to discuss it more - none of these solutions are what I would consider "perfect" - all of them involve trade offs. So would be interested to hear your and Seb's opinions on it too

@IanMendozaJaimes @sebastianmontero

**Comment by IanMendozaJaimes** [comment]
Yes, you are right, to have another table with floating values is cleaner, easier and prevent unexpected bugs. 

The only impact it may have on the contracts is in referendums. The function `referendums::send_change_setting` is calling `settings::configure`. I don't think that's problematic as it just needs to know first which action to call (to configure ints or floats). The function `referendums::send_change_setting` is called only within the test function `referendums::run_testing` so I don't know if this is relevant for this ticket.

**Comment by sebastianmontero** [comment]
Hi @n13, how about keeping the same table to store both floating and int, and just relying on the client of the setting knowing if its a floating value or an int value, and using it accordingly,  this wouldn't require any changes.

**Comment by n13** [comment]
Yes I think both approaches have advantages and disadvantages but I think keeping them separate would be best. Maybe enforce unique names across both tables in the setters
