### ISSUE TITLE
Organization Scores + Status

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#20]
Now we have user scores calculating, add org scores
## Constitution
https://docs.google.com/document/d/1vg95Bw4Pzsqe4DXPusiyD2hAU-HCI-37c0AAZSXxC68/edit?disco=AAAAGUxQgpM
## Overview
<img width="597" alt="image" src="https://user-images.githubusercontent.com/65412/77232702-f48d5b00-6ba2-11ea-817f-2c5cba68d5fa.png">

## Regeneration Score (Biosphere Score)

Tasks:

- [ ] Implement Regen Score calculation
- [ ] Add unit tests

### Voting from -7 to +7

- A user can vote on an org with a value from -7 to +7
- A vote is multiplied by the user's reputation score
- Formula: points * [rep score]

### Regen Points

- "When an org has more than 1000 points, its regenerative score is set to the median of the received votes"
- "When an org has less than 1000 points, its regen score is 0"

### Regen Score
- Ranking regen points from 0 - 100

## Accounts referred = CBS

* Create cbs table in org

**Comment by n13** [comment]
> To progress to a Regenerative Organisation you:
1. Plant: [​400] Seeds
2. GainReputation:Obtaina​rankingof[50]​.
3. Exchange: ​transactions​ with [​50] ​Reputable Organizations &/or Citizens
4. Refer:[​10]Visitor​accounts
5. Refer: [​5] Resident​ accounts

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
1. In the organizations contract there are two methods `addregen` and `subregen`, they are like the voting action, but they allow to vote for an organization at any time, is that right?
2. Will the ranking 0-100 be calculated from all orgs the same way it is calculated for users?, does it mean an org that became a regenerative org could lose that status if it is ranked less than [50] at some point?
3. The regen score should be calculated as soon as an organization gets > 1000 points? or should it be calculated when calling onperiod or any other function?
4. Is the transaction score the same as economic score?, and how could I calculate that score?, is there a way to see the seeds an org is moving? the app tracking functions does not record the transactions info

**Comment by n13** [comment]
> Hello, I have some questions:
> 
> 1. In the organizations contract there are two methods `addregen` and `subregen`, they are like the voting action, but they allow to vote for an organization at any time, is that right?

> 2. Will the ranking 0-100 be calculated from all orgs the same way it is calculated for users?, does it mean an org that became a regenerative org could lose that status if it is ranked less than [50] at some point?

Good question - if it has less than 1000 points it should lose the status.

Ranking is based on others so I don't see how can can punish orgs when we have lots of really good orgs? @Rieki7 

> 3. The regen score should be calculated as soon as an organization gets > 1000 points? or should it be calculated when calling onperiod or any other function?

If > 1000 points, it gets a regen score
If < 1000 points, it loses regen score (score goes to 0, which in our system means it's removed from the table)
Rank is calculated periodically, maybe daily is OK - same we calculate rank for users except does not have to be hourly


> 4. Is the transaction score the same as economic score?, and how could I calculate that score?, is there a way to see the seeds an org is moving? the app tracking functions does not record the transactions info

We need to record transactions I suppose. For now we can use history contract transactions same as we do for non-org users but for orgs we will eventually need to record both incoming and outgoing and count both. For individuals we only count outgoing.

So there has to be a separate history table entries for orgs that count incoming and outgoing. Other than that it can work the same as individuals

If this is too vague, let's use the same history entries now as we do for individuals and I can create a detailed spec later.

I think we can still scope by account name, but we need to record both incoming and outgoing for orgs - not too bad perhaps, maybe it needs an extra field specifiying if it's outgoing or incoming, I think that might affect the tx score calculation

Tx scores are calculated the same as they are for users after that - I can spec this out more.

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
- The range from [-7] to [7] means that a user can chose freely how much points the user wants to give?
- Are the score tables and methods right in the orgs contract? or should they be in harvest?
- The documentation page 41, says that the regen score is calculated based on the [median] regen points an org is given. By the median you mean the median from statistics right like the middle value?
- the status in the organizations table is an integer, is that right? shouldn't it be a name instead?

I just want to clarify if I understood well:
- For the regenerative score, I am using the points given by the users, and then calculating the median of this points per organization and rank them based on that.
- For the transactions score, I am using the history transaction table as you suggested, and I am calculating the transaction points with the same method used for user accounts. I only created other table for storing the trx points for orgs only.
- For the community score, I am using the cb_points given in the referreward function from accounts contract, but I add these points to other table just for orgs to rank them.

I also want to mention:
- The transactions score calculation uses a fixed max quantity, it has a comment that says it should be a parameter

**Comment by n13** [comment]
> Hello, I have some questions:
> 
> * The range from [-7] to [7] means that a user can chose freely how much points the user wants to give?

Need to look that up I believe it was tied to reputation somehow.

> * Are the score tables and methods right in the orgs contract? or should they be in harvest?

Our policy on scores and points is to keep where it makes the most sense. There's an added efficiency of keeping the scores and points in the same table - so we should follow the same pattern everywhere we have scores (rank) that gets calculated from points. 

Only way to manage this is when all our various ranks work exactly the same way.

> * In the documentation, in the page 41, says that the regen score is calculated based on the [median] regen points an org is given. By the median you mean the median from statistics, like the middle value in an array? If this is the case, do you have any idea of how to calculate it in less than O(n) for the votes table?

I've been looking into this, ranking and median is both O(n) unfortunately. 

So we will have to have a function that goes and calculates it every (hour) or other time interval.

> * the status in the organizations table is an integer, is that right? shouldn't it be a name instead?
> 

Happy to make it a name - there was no specific reason to make it an int

> I just want to clarify if I understood well:
> 
> * For the regenerative score, I am using the points given by the users, and then calculating the median of this points per organization and rank them based on that.
> * For the transactions score, I am using the history transaction table as you suggested, and I am calculating the transaction points with the same method used for user accounts. I only created other table for storing the trx points for orgs only.

-> I am in the middle of adding another tx_org table in the history contract that keeps the incoming transactions for orgs only

So for individuals we only keep outgoing as we have been doing, for orgs we also keep incoming and they are in another table.

> * For the community score, I am using the cb_points given in the referreward function from accounts contract, but I add these points to other table just for orgs to rank them.

Yes that's fine for now - we will have to split off CB points for orgs and individuals eventually though they should be kept in 2 different tables and rank against the same category.

> 
> I also want to mention:
> 
> * The transactions score calculation uses a fixed max quantity, it has a comment that says it should be a parameter

Thanks for noticing, please make it a parameter in this case

**Comment by IanMendozaJaimes** [comment]
Hello, I have some more questions:
- What are the requirements to become a Reputable Organization?
- In the documentation page 37, what does "Rules: [TBD]" mean?
- This requirement to become a Regenerative organization: _Exchange: transactions with [50] Reputable Organizations &/or Citizens_, does it mean [50] different reputable or regen orgs &/or citizens?, or [50] transactions in total with any Reputable or regen or citizen?. Do you think this requirement should be stored when a transaction occurs?, to avoid iterating through the entire history of transactions for an organization looking for citizens or reputable or regenerative orgs.
