### ISSUE TITLE
Use buckets to distribute dSeeds and planted bonus alongside harvest

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#224]
## Feature
**Deferred Seeds**  (dSeeds) are Seeds held by the escrow contract which are triggered by the Go Live event. 

Each user can have between 0-N locks and there may be locks held by non-Seeds users as well. Each lock has an amount of dSeeds and a beneficiary. We will only consider locks with the "golive" event trigger - we ignore all other locks, they are not by definition dSeeds. 

Currently once the golive event is triggered by the DHO - the dao.hypha contract - all dSeeds would be paid out to their beneficiaries.

What we want to do instead is to pay them out with the harvest over time.

## Spec

Some of this spec is a sample implementation - use as a guideline as to what it's supposed to do, but if there's something missing, or there's a better implementation, feel free to do that.

### Harvest changes
while dSeeds > 0, 50% of the harvest is paid out to dSeeds, the rest is paid out as usual.

### escrow changes
**ACTION golive**
migrates all golive locks to dseeds bucket contract
iterates over all locks with deferred transactions

On each lock
calls migratelock(user, quantity) on bucket contract
transfers quantity of seeds to bucket contract
deletes lock

### **dSeeds contract** (or table inside an existing contract like escrow or harvest)

**ACTION migratelock(user, quantity)** 
called from escrow
consolidates holdings of users, e.g. each user ends up with a single number of Seeds to be paid out to them
calculates the total number of Seeds remaining to be paid out (sum), stores it in a sizes table

**ACTION payout(asset quantity)**
pays out a total of quantity
iterates over all table entries, calculating the % of total outstanding for each user, e.g. perc = user_seeds / total_seeds_to_be_paid_out. Total seeds to be paid out is the sum of all user table entries.
calculate amount to be paid out: amount = min(user_seeds, perc * quantity)
subtract amount: user_seeds = user_seeds - amount
transfer amount in Seeds -> user
uses deferred action to iterate over all users
at the last user, updates the total: new total = old total - quantity, so total needing to be paid out is decreased.

## Planted Bonus
The same apples for planted bonus. 

This should be a separate ticket. But the idea is that we have a 30% planted bonus which should be paid out to people who planted in the exact same way. @Rieki7 not sure this planted bonus could be mixed in with the dSeeds (just added to the dSeeds balances). That's probably the easiest way then we only have to call the migrate lock action from the harvest contract, going over planted scores. Or even just from the dSeeds bucket contract, accessing planted scores at a certain date.

**Comment by IanMendozaJaimes** [comment]
Just to confirm if I understood: 

Currently in the escrow contract, if you want to create a lock for a certain beneficiary, you have to transfer the Seeds to the escrow contract so you become a sponsor and then you can create a lock, holding those Seeds so they can be claimed by the beneficiary. 

The idea, is that locks that are triggered by go live doesn't use the sponsor's balance, instead once the go-live event is triggered, these locks' amounts will be summed up so the beneficiary has a bucket in the dSeeds contract like a promissory note that will be paid out through the harvest.

Depending on the percentage of total amount to be paid out in the dSeeds contract a user has, it is the amount of the harvest the user will receive on their buckets.

Whenever the user want's, she can withdraw her accumulated amount of Seeds.

Is that correct?

I also have another question:
- When you say 50% of the harvest, does it mean the 50% of the whole harvest? so for example, there are 4 mayor buckets: orgs, users, regions and dho, then this means while dSeeds > 0, the 50% of the harvest will be designated to those 4 buckets and the other 50% is for paying the dSeeds

**Comment by n13** [comment]
> Just to confirm if I understood:
> 
> Currently in the escrow contract, if you want to create a lock for a certain beneficiary, you have to transfer the Seeds to the escrow contract so you become a sponsor and then you can create a lock, holding those Seeds so they can be claimed by the beneficiary.
> 
> The idea, is that locks that are triggered by go live doesn't use the sponsor's balance, instead once the go-live event is triggered, these locks' amounts will be summed up so the beneficiary has a bucket in the dSeeds contract like a promissory note that will be paid out through the harvest.
> 

I would suggest to actually transfer the Seeds to the bucket holding contract which is a different kind of specialized escrow contract that actually pays out with the harvest. 

This way we keep the escrow contract clean. 

> Depending on the percentage of total amount to be paid out in the dSeeds contract a user has, it is the amount of the harvest the user will receive on their buckets.
> 

I don't think users should have buckets, just the one bucket of paying out Seeds according to percentage distributions. 

> Whenever the user want's, she can withdraw her accumulated amount of Seeds.
> 

I think the Seeds can just be sent to the user, rather than keeping a balance of how much they're entitled to withdraw?

That's 2 different ways to do it.

Let's say the new contract is called he.seeds for harvest escrow .seeds 

In my proposed solution, on golive, all go live locks Seeds are transferred to he.seeds

all go live balances are entered into he.seeds so we know who is entitled to how much

Then there's a harvest function call that has only the value of total seeds to be distributed according to the harvest

So let's say the total to-be-minted seeds for a harvest would be 1000 seeds

Then we only mint 500 and distribute according to the normal buckets, and we call the he.seeds with the value 500, so it will go and distribute 500 of the seeds it is already holding, to the beneficiaries, according to their % of the total. 

So that's what I was proposing

In your wording, it sounds more like in escrow.seeds the balances are accumulated so each user has only 1 lock, then same thing we figure out the total and can calculate each user's % of the total, and unlock a certain amount - the amount unlocked would be stored in a separate balance table I suppose?

Not sure which approach is better, mine seemed straightforward to me, but maybe there's something I'm missing. 


> Is that correct?
> 
> I also have another question:
> 
> * When you say 50% of the harvest, does it mean the 50% of the whole harvest? so for example, there are 4 mayor buckets: orgs, users, regions and dho, then this means while dSeeds > 0, the 50% of the harvest will be designated to those 4 buckets and the other 50% is for paying the dSeeds

Exactly. 

We would figure out the number to mint, but then only mint 50% and let the contract pay out the other 50% - move them from locked to unlocked in some fashion, see above

**Comment by IanMendozaJaimes** [comment]
Hello @n13, then can you confirm this: the dSeeds contract is all about paying out the Seeds held by the escrow contract at the same time the harvest is distributed, so the dSeeds will be paid out hourly right?, because this is the frequency the harvest is distributed.

**Comment by n13** [comment]
> Hello, I have another question:
> 
> * Using your example above, let's say the harvest would be 1000 seeds, then 500 seeds will be paid out normally, but those 500 seeds are for the four buckets? so will they be for orgs, users, regions and dho?, so it means that meanwhile dSeeds > 0 the orgs, users, regions and dho will receive 50% less harvest?, unless some account had a percentage in the he.seeds contract because then that account will receive more seeds equivalent to min(user_seeds, perc * quantity), quantity = 500 in this example

Yes, exactly. The idea is that initially the harvest is used to pay out dSeeds in a non-invasive manner - with the harvest. 

So everyone else will be getting less!

**Comment by n13** [comment]
I am confirming this with Rieki...

**Comment by n13** [comment]
Ok had an idea we actually just need 2 actions, ontransfer(from, to, amount, memo) and payout(asset amount)

Then we can use ontransfer for any incoming transfer, doesn't matter, it makes it all so simple

pool.seeds contract

ontransfer() - triggered by incoming SEEDS transfer, memo contains beneficiary Seeds (or Telos) account

- parses memo to find beneficiary
- adds to balance of beneficiary in balances table
- adds amount to total amount - sizes table for example "total"

payout() - as before takes total and runs through balances table to figure out payouts

So pool.seeds only has these 2 methods

On escrow goLive, for each lock, we call transfer with the beneficiary in the memo, adds it to the pool

That's it!

Then when we get more goLove escrow Seeds, we also transfer them on to the pool the same way, so new bonuses that are paid out are simply added to the pool. 

This was very complex in my mind but like that it's actually simple, I think
