### ISSUE TITLE
Flagging Feature

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#231]
Action: Flag another user

Flag points - same as rep points calculations

Resident has 10
Citizen has 20

x rep multiplier, so for example rep multiplier is 1.8, x 20 base points = 38 points for a citizen in the 90% percentile

Once a user has 100 flag points, they get the "punish" action triggered on them, which ripples negative reputation out to all who vouched for them

## Spec

Add an action "flag" (from_user, to_user)
Add a table flag_table
Flag_table keeps flag points, scoped by receiving user, list of users who did the flagging

User can call flag on another user only once
User can remove their flag on another user
Flag points are checked any time there is a new flag incoming
When the flag threshold is triggered the punishment is executed - it cannot be undone since it ripples out
Flag threshold is a setting of high impact "flag.thresh"

Constitution & Game guide pp 53

## Implementation - 

Possible to continue to remove reputation of the target after the 100 pt threshold.

Try to do it like this:
- Accumulate up to 100 flag points (threshold) without taking action
- Once 100 is reached, we take away these 100 and any extra points that get in there
- Once 100 is reached, additional flags from people directly remove reputation in the same amount

Example
A flags Z for 40 points - nothing happens, but it is stored in the flag table
B flags Z for 35 points - nothing happens
C flags Z for 30 points - that's 105 total so A gets punished for 105 points, and they ripple out to vouchers
D flags Z for 20 points - A gets punished for an additional 20 points, which also ripples out
... and so on

The idea is if a scammer managed to get a lot of reputation, this way it can be removed again

**Comment by juliolrmonteiro** [comment]
So each user has their own flagging "power" that can only change when their rep changes. They can flag as many users they want, and each time they flag someone the current full "flagging power" is applied. If they want to "correct" they flagging, they have to remove the past flag and reapply a flag.

- Suppose A(Citizen with 1.5 rep) flagged Y for 30 points
- Then in the future A increased his rep to 2.0.
- User A (Citizen with 2.0 rep) flags user X with 40 points
- If they want to correct their flag on Y, they have to remove the flag first (-30 points) and reapply (+40 points).

**Comment by IanMendozaJaimes** [comment]
Hello I have some questions:
> User can remove their flag on another user
- Does that mean that a user can only flag one user at a time? I mean if user A has flagged user B, then A can not flag user C until A removes her flag from B?
- If a user removes their flag from A, then A's flag points reduce?, for instance, A has 90 points, and B removes her flag which was giving 20 points to A, then A ends up with 70 flag points in total
- If the answer to the previous question is yes, what would happen if:
a user A has let's say 110 flag points, so it means A has already received a punishment of minus 110 rep points, B removes her flag and A ends with 90 points, and then B flags A again. At this point A has 110 flag points again, but should A only receive a punishment of 20 points or A should receive -110 rep points again, or A should not be punished because B has already participated in a previous punishment

**Comment by juliolrmonteiro** [comment]
> * Does that mean that a user can only flag one user at a time? I mean if user A has flagged user B, then A can not flag user C until A removes her flag from B?

I don't think this is what was meant, you can flag as many users as you can, but only one time per user.

> * If a user removes their flag from A, then A's flag points reduce?, for instance, A has 90 points, and B removes her flag which was giving 20 points to A, then A ends up with 70 flag points in total

Seems right, but you should deduct the points that were gained at that time, not the current "flagging power" of the user.

> * If the answer to the previous question is yes, what would happen if:
>   a user A has let's say 110 flag points, so it means A has already received a punishment of minus 110 rep points, B removes her flag and A ends with 90 points, and then B flags A again. At this point, A has 110 flag points again, but should A only receive a punishment of 20 points? or A should receive -110 rep points again?, or A should not be punished because B has already participated in a previous punishment

Ah, this is a good catch! I think the user should only get the flagging penalty ONCE too. So, if you total ever reach above 100 points, you get the punishment, then no matter you score from that point on (you can't be "unpunished", right? Or the rippling of that would be crazy).

Maybe, in the future, you can have multiple flagging thresholds, like 100, 500, 1000 points, that once you reach for the FIRST time, you get another flag/punishment, but this is not in the constitution yet.

**Comment by IanMendozaJaimes** [comment]
Hello @juliolrmonteiro, 
> Ah, this is a good catch! I think the user should only get the flagging penalty ONCE too. So, if you total ever reach above 100 points, you get the punishment, then no matter you score from that point on (you can't be "unpunished", right? Or the rippling of that would be crazy).

But that contradicts the example given above:

> D flags Z for 20 points - A gets punished for an additional 20 points, which also ripples out

I think a convenient way to manage this is to not reduce your score if someone removes their flag and the flagged user has over 100 points (in this case). Because as you said, you can not be unpunished, so if you have that score, then you have received a punishment and doesn't matter if someone unflags you, and if another user flags you, you will receive a punishment of only the extra points.

I also think it would be a good idea to include the date a user flagged you, to prevent that someone flags, unflags, flags, unflags, etc, on purpose

**Comment by n13** [comment]
> So each user has their own flagging "power" that can only change when their rep changes. They can flag as many users they want, and each time they flag someone the current full "flagging power" is applied. If they want to "correct" they flagging, they have to remove the past flag and reapply a flag.
> 
> * Suppose A(Citizen with 1.5 rep) flagged Y for 30 points
> * Then in the future A increased his rep to 2.0.
> * User A (Citizen with 2.0 rep) flags user X with 40 points
> * If they want to correct their flag on Y, they have to remove the flag first (-30 points) and reapply (+40 points).

@juliolrmonteiro yes but that's only a side effect of not having dynamic reputation throughout the system

We aim to make it more dynamic. I don't think anyone needs to correct their flag?! But the way you describe it, that would work. Since it's actions an app - like the light wallet - could issue 2 actions in 1 transaction and do both all in one go. Basically an "update" function.

**Comment by n13** [comment]
> Hello @n13, I have some questions:
> 
> > User can remove their flag on another user
> 
> * Does that mean that a user can only flag one user at a time? I mean if user A has flagged user B, then A can not flag user C until A removes her flag from B?

No users can flag as many ppl as they like

The flag table would probably be scoped by the receiving user. E.g. under the "illumination" scope, there'd be all flags that I have received from others (that account "illumination" received from other users)

> * If a user removes their flag from A, then A's flag points reduce?, for instance, A has 90 points, and B removes her flag which was giving 20 points to A, then A ends up with 70 flag points in total

Yes. I think we don't need to store the total flag points (I hope...) ... then whenever we need someones flag points we can just calculate it from their table (although writing this if they got a lot of flags that may be an issue.. hmm... maybe the flag table can contain a special element ".total." which contains the total of all points received and is updated on every change to the table. 

> * If the answer to the previous question is yes, what would happen if:
>   a user A has let's say 110 flag points, so it means A has already received a punishment of minus 110 rep points, B removes her flag and A ends with 90 points, and then B flags A again. At this point, A has 110 flag points again, but should A only receive a punishment of 20 points? or A should receive -110 rep points again?, or A should not be punished because B has already participated in a previous punishment

Ok that's a good question! We could store a total punishment value in the same table too that shows how much points they got punished for. 

So we would want to aim for not punishing them for 100+ points twice, only punish them for how many points they got total.

Maybe if > 100, then users can't remove their flag anymore. That's one option. Then this can never happen.

Or we track the total punish points and if (total punish points) are > (new punish points after any number of removals and adds) then nothing gets added to the punishment. So we keep the total they were punished for, in the above example, B removing their flag changes nothing, B adding it back in brings the total to 110, but they were already punished for 110 so nothing is added.

If that makes sense. 
Then the punish count only starts when 100 is exceeded (before that we ignore flags), then the rule would be if the total punish points that already exist
