### ISSUE TITLE
Accept Vouch and Un-vouch on penalty

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#233]
## Overview

We will have forward penalties where users lose reputation gained from vouching

But in the current system we don't have a way to do that

Currently vouch points are added up and capped at 50

In the new proposed system we remember each vouch, and the points, in a table scoped by user

Then in the places we use these vouch rep points, we count max. of 50. The calculation can be redone when a vouch falls away.

## Spec
Just like penalty points, keep vouch points in a table thats scoped by user
Alter the main rep points of a user when the total changes - I think we can figure this out on each additional vouch

## Penalty rippling forward 

When a user gets penalized, the users this user vouched for lose the vouch points they gained.

Example user A gets penalized
A vouched with 22 points for B
B now loses those 22 points. B's reputation might change from that if they had less than 50 points, or if they had more than 50, but after the penalty now have less than 50. 

B's reputation would not change if they still have >= 50

**Comment by juliolrmonteiro** [comment]
Check Constitution at this point: https://docs.google.com/document/d/1C4w9Ol8VGabCIcQDVPDrwcTRoJXBqhrb7VjslwQbUGU/edit#heading=h.95nxy840131q

These 3 lines are relevant:

Index | Name / Action | Description / Calculation | Setting / | Setting ID | Impact | Contract
-- | -- | -- | -- | -- | -- | --
  | Flag Reputation Loss Limit Before Effect | Members lose reputation when flags reach a minimum of N flag points. This triggers the reputation loss for any account that vouched for the flagged account. | (-) 100 Rep | flag.thresh |   |  
-- | -- | -- | -- | -- | -- | --
  | Flag Base Points | Each flag comes with N negative reputation points | Resident = (-) 10 Citizen = (-) 20 | flag.basept |   |  
-- | -- | -- | -- | -- | -- | --
  | Vouched Flagged Account | Lose reputation if an account you have invited or vouched for is fully flagged | (-) 50 Rep |   |   |  
-- | -- | -- | -- | -- | -- | --

So it seems the voucher account loses 50 points, while the vouched account that got flagged loses 100.

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
- Should the function `unvoche` be implemented as an option for the sponsor?
- Related to the example above, when A is penalized, then B losses her 22 vouch points, but this should be considered like an `unvoche` action or instead, A remains as a sponsor in the vouche table but A gives 0 vouch points now

About the implementation of the new vouch table, I think it would be convenient to not scope the table, and instead use some secondary indexes, like this:

      TABLE vouch_table {
        uint64_t id;
        name account;
        name sponsor;
        uint64_t vouch_points;

        uint64_t primary_key() const { return id; }
        uint64_t by_account()const { return account.value; }
        uint64_t by_sponsor()const { return sponsor.value; }

        // just in case some batches are needed in the future
        uint128_t by_sponsor_account()const { return (uint128_t(sponsor.value) << 64) + account.value; }
        uint128_t by_account_sponsor()const { return (uint128_t(account.value) << 64) + sponsor.value; }
      };

in that way it's easy to know who is your sponsor, or to know who you are sponsoring. Maybe we can scope it like in the flags table .total to keep track of the total sum of the vouch points a user has. @n13 what do you think?

**Comment by n13** [comment]
@IanMendozaJaimes I agree on the table, having both account and sponsor indexes will be more flexible.

A sponsor can vouch for someone, and also unvouch for someone. 

The main goal of this is to be able to have forward rippling penalties

The use case is, user A was a bot, but vouched for all these other bots

Now we found out A was a bot, penalize them, and everyone they vouched for - all the other bots - lose the points.
