### ISSUE TITLE
5 levels of organizations

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#242]
## Spec

This is a change to the constitution - we need 5 levels of orgs, not just 3. 

Orgs have 5 levels of sustainability scores, instead of three
Regular, Reputable, Sustainable, Regenerative, Thrivable

There are certain requirements and benefits to each level

pp. 62 of the constitution

![image](https://user-images.githubusercontent.com/65412/109910138-69897000-7ce2-11eb-915f-0a8ead1d73fa.jpeg)

**Comment by n13** [comment]
This method neesd to reflect 5 multipliers

```
double history::get_transaction_multiplier (name account, name other) {
  double multiplier = utils::get_rep_multiplier(account);
  
  auto oitr = organizations.find(account.value);
  if (oitr != organizations.end() && oitr -> status == regenerative_org) {
    multiplier *= config_float_get("regen.mul"_n);
    // Add more multipliers for org
  }

  auto bitr_account = members.find(account.value);
  auto bitr_other = members.find(other.value);

  if (
    bitr_account != members.end() && 
    bitr_other != members.end() && 
    bitr_account -> bioregion == bitr_other -> bioregion
  ) {
    multiplier *= config_float_get("local.mul"_n);
  }

  return multiplier;
}
```

And other changes...

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
1.- Currently the status variable starts from 0 (Regular org), do you want it to start from 1?, a migration would be needed but not to change the table structure, only to add +1 to all the existing orgs.
2.-  There is a table in the history contract that stores when an org becomes reputable and one that stores when an org becomes regenerative, so I think it'll be better to have just one table scoped by type, what do yo think?

**Comment by juliolrmonteiro** [comment]
Regarding (1), why do you think it's best to have status starting at 1?

Regarding (2), yes makes sense to have a single table scoped by type.

Ah, this would be so much easier with Badges :D

**Comment by IanMendozaJaimes** [comment]
(1), I actually think is better to start from 0, in that way is cleaner to map their status in an array, it was just more like an option in case someone wants it to start from 1, but if not, I prefer it from 0
(2) great!

**Comment by n13** [comment]
Starting from 0 is always better in programming :) 

While starting from 1 always introduces issues. 

So I agree with @juliolrmonteiro and @IanMendozaJaimes here
