### ISSUE TITLE
Voice decay is too fast?

### ISSUE THREAD

**Issue by juliolrmonteiro** [JoinSEEDS/seeds-smart-contracts#313]
Check if it's a settings issue, or recheck the unit tests.

**Comment by n13** [comment]
set decay percent to 11 from 15

![image](https://user-images.githubusercontent.com/65412/117619918-71620680-b1a2-11eb-8ce8-b7b77264c964.jpeg)

**Comment by n13** [comment]
Closing this bug, thanks @juliolrmonteiro
