### ISSUE TITLE
Make Token transfer more efficient

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#315]
## Overview

Part (1) of #314 

Currently token transfer accesses the users table, loading entire user objects, 4 times

2 times in the token contract and 2 times in history contract on 
```
void history::trxentry(name from, name to, asset quantity) 
```
## Token contract
This is easy to remove, we don't need user objects we only need planted scores. We can use planted balances to determine if someone is a user - all users have an entry - and handle the special harvst.seeds entry in planted (ignore, not a user).

## History contract

The latter more complicated as we are checking for organization status of an account - we could put that in the delayed transaction

I also found a bug with history entries and delayed transactions, made another ticket for that here: https://github.com/JoinSEEDS/seeds-smart-contracts/issues/316

Overall the strategy should be to keep the call into history as an inline action, as we may need this for other purposes, and we don't want to change the token contract, but perhaps change history contract to delay computationally expensive tasks into a deferred transactions. 

Or, if we clean up the users table and restrict the size of the user object, this won't be an issue ;)

**Comment by IanMendozaJaimes** [comment]
Hello @n13, I think the most expensive part in history::trxentry is to check whether the accounts are orgs or individuals and the get_rep_multiplier function as it checks the orgs table and the regions table.

Maybe what I can do is to keep the part that saves the totals (from line 195 to line 228) and leave all the daily_transactions_tables stuff in a deferred transaction, that includes the calculation of points the transaction receives. Although the checking if an account is an org would be still needed in the normal action, but I can use the orgs table instead of the users table. Is that ok?

I also think this won't be an issue if we can restrict the user object's size

**Comment by n13** [comment]
I think we should use orgs table instead of users table - basically avoid users table whenever we can in the token transfer function.

Not sure we need the deferred tx, that would work but maybe let's do the migration first

**Comment by n13** [comment]
> Hello @n13, I think the most expensive part in history::trxentry is to check whether the accounts are orgs or individuals and the get_rep_multiplier function as it checks the orgs table and the regions table.
> 
> Maybe what I can do is to keep the part that saves the totals (from line 195 to line 228) and leave all the daily_transactions_tables stuff in a deferred transaction, that includes the calculation of points the transaction receives. Although the checking if an account is an org would be still needed in the normal action, but I can use the orgs table instead of the users table. Is that ok?
> 
> I also think this won't be an issue if we can restrict the user object's size

That sounds good to me. Makes sense to have all calculations in the deferred tx. 

I think that's how we got into trouble, we added too many things to this transfer function, but really what should happen is that transfer only checks planted - to see if you have enough gas - and everything else that may happen and get calculated can be packed into the deferred transaction

**Comment by n13** [comment]
Deprioritize
