### ISSUE TITLE
Citizen Path Change [Referendum #4]

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#438]
## Implementation Spec

Change it so when 3 or more citizens vouch for a user, the user can instantly become a citizen

Remove the requirement for "inviting members"

## Original Spec
A. Path from Visitor to Citizen: becoming a citizen doesn’t require inviting members any longer but rather being vouched for by 3 Citizens during a Citizen Ceremony. 

This is a project in itself (SEEDS Citizenship), as it requires further design of the process for neighbourhubs, organisational implementation at the SEEDS level and technical implementation in the apps. 

Implementation Team for the SEEDS Citizenship project:
RE: → changes to the SEEDS Guide
MoM: → changes to the rituals and people process for finding Citizens to receive vouches
Hypha: → changes to the Smart contracts, Passport and Light Wallet

**Comment by chuck-h** [comment]
https://discord.com/channels/722537361480613950/969298065490067466/974471310895882240

"[...] I therefore suggest that we take a "shortcut" implementation approach which provides a means to enroll new citizens through the new ceremony process. Specifically, let us create a new blockchain action which directly promotes an account to citizen status [...]."

**Comment by n13** [comment]
Original change was not good enough, made another commit for this

**Comment by n13** [comment]
Waiting for apps to update before deployment
