### ISSUE TITLE
Bioregions

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#45]
## Phase 1 Minimal Implementation [SEEDS and Hypha]

Bioregions are also present in the Hypha DAO and this is why I suggest a minimal structure for them - a contract that captures bioregions without having much other information or function.

### Specs
* bioregion contract bio.seeds
* table with bioregion - id (telos name), name (string), location (json string with lat/lon), status, paused
* each seeds accounts belongs to 0 or 1 bioregions - this can be an additional field on account, or a separate table, additional field would be empty if no bioregion
* location is a string in JSON format - we will initially store long/lat so we can at least show an indicator on a map, we might later add fancy formats to describe the extent of a region more accurately, if the need arises.
* bioregion can be created with 0 users, becomes active at **[144]** users (setting)

## Actions

Create / Change can either be done by staking and owner like an org - or by admin on whitelist

* ACTION create - checks that name is .bdc, creates telos account with this name and public key
* ACTION change - cannot change ID, can change everything else
* ACTION addadmin (name) add an admin to whitelist who can add and remove bioregions
* ACTION removeadmin (name) remove an admin who can add and remove bioregions
* ACTION pause (name) pause a bioregion. Or 'suspend'

## Deployment

- [x] settings
- [x] bioregions
- [ ] onboarding

Phase 2 see #73

**Comment by jmsofarelli** [comment]
Where should the `bioregion_table` be created? In the `accounts` contract`?

**Comment by jmsofarelli** [comment]
_"Existing tables of proposals, voice, referendums, voice and settings are moving to the "earth" bioregion"_
In order to accomplish that, should we just add a new field called `bioregion_id` to all of these tables?
Should we do the same with `user_table` and set the default value to "earth"?

**Comment by n13** [comment]
Bioregion is its own contract and has its own tables and actions

user_table (or users, actually) gets a bioregion - each user can have one

For the proposals and so on, we could put a bioregion id on each one, with earth as default, or scope them. Scoping seems a natural way to do this. Very neat.

**Comment by n13** [comment]
Done
