### ISSUE TITLE
Rename "Staking" to "Backing" in the rainbow contract

### ISSUE THREAD

**Issue by alexprate** [JoinSEEDS/seeds-smart-contracts#456]
The mechanism as described by Rieki in his rainbow paper and as developed by Chuck is more of a backing mechanism. The classic staking - as in locking up a token for a period of time doesn't yet exist in the contract. It might be confusing to keep the terminology Staking for what is more of a backing.

**Comment by alexprate** [comment]
@chuck-h I'm in favour of updating the name from staking to backing to avoid confusion.

**Comment by chuck-h** [comment]
code changes done in PR #460 . (Video tutorials remain using "staking" at this time.)
