### ISSUE TITLE
Voting increases reputation

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#57]
## Spec

See #52 

Participating in voting gains +1 rep point

## Implementation

- proposals has a table of who voted already - if you have not voted, you get entered there, and gain +1 rep. 
- the table is erased at the end of the cycle
- must vote on all available proposals before a reward is received
"Citizens are required to vote "Trust", "Distrust" or "No Opinion" on each proposal in order to gain the Reputation rewards as detailed in the Reputation section."

Problem is there is no way to drop a table all at once, and for many records this may exceed transaction allocated time.

So another solution would be to integrate this will assigning trust tokens, which must happen at the beginning of a new cycle, and which will have to be batched anyway to prevent timeouts. Probably a better idea.

## Deployment
Deploy proposals

**Comment by jmsofarelli** [comment]
"proposals has a table of who voted already - if you have not voted, you get entered there, and gain +1 rep"
Is this the `vote_table`?
Does it mean that I get 1 rep for each proposal I vote? For example: if I vote in 3 proposals, I get 3 rep?

**Comment by jmsofarelli** [comment]
_"must vote on all available proposals before a reward is received"_
Currently, using the Passport app, I can't define the amount of Trust Tokens used in my vote. 
For example, in the current cycle, there are 4 open proposals and I go initially 75 Trust Tokens. 
My first vote took 70 Trust Tokens and my second vote toke the remaining took the remaining 5 Trust Tokens. I could not define the amount of Tokens used in each proposals, I can change the amount used and I will not be able to vote in all of them. How can we solve this sort o problem?
Also, in the `vote`table` there is a `boolean`field called favour. How can we represent 3 options ("Trust", "Distrust" or "No Opinion") using only a `boolean`?

**Comment by IanMendozaJaimes** [comment]
Hello, we have some questions:
1. Voice is the same as Trust Tokens?
2. Do we have to handle the erase of the `vote_table`?
3. If we have to erase the table, do we have to manage the batching?, in that case, do you have any suggestions? as vote_table is scoped by proposals, it seems it could be difficult to integrate the erase method with assigning trust tokens.
4. *"Must vote on all available proposals before a reward is received"* , do we have to handle this? I mean, to check whether the user is eligible to receive a reward an give it to them?
5. The  `No Opinion` option appears as `Abstain` in the documentation, which one should we use?

**Comment by n13** [comment]
@IanMendozaJaimes 
- The wording is weird, sorry, no I meant creating a new table that only shows who voted. Could call it participants.

- We somehow need to check whether a user has voted on all existing proposals, and has not voted neutral on all of them.

So the new table could look like this

```
participants (table scope, not proposal scope)
account  |  nonneutral (bool)  |  count (int)  |  complete (bool)
```

Then we could compare count with the number of active proposals and know whether or not this user will gain trust tokens

- its 5 trust tokens when user has voted on all proposals and has voted non-neutral for at least 1. Voting non neutral sets the nonneutral flag to true)

- we don't want to erase the votes table per proposal - we want to keep this data

- we can hand out the reward when we erase the table - since it's an erase action it can use a delay action to call itself, limit to 200 rows, and call addRep() with a "send" on accounts.

**Comment by n13** [comment]
Done
