### ISSUE TITLE
Basic Delegate Trust

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#58]
## Spec

Delegate Trust
Citizens may delegate voting rights to another Citizen. 
This earns Citizens rewards as described in the Reputation section of this paper. 
Delegations mimic the relative voting of the delegatee. 
Example: If delegatee casts 1/10 of their Trust Tokens on a proposal it follows with 1/10 of the Trust Tokens of the delegator.
 [%] of Trust Tokens cast delegatee = [%] of Trust Tokens cast of delegator 

## Implementation

Could do this relatively easily with a delegations table on the proposals contract

If one has made delegations, they can't vote themselves
delegations can have a weight 1 - 100 (fixed to 100% for the first implementation)

**Comment by juliolrmonteiro** [comment]
Delegate votes need to be by Categories (Alliances, Proposals, Referendums for now)
You can only assign one Citizen to vote for you on that category.
You voting power is fully available on all Categories (not split)

**Comment by IanMendozaJaimes** [comment]
Hello I have some questions:

- How long does voice delegation last? I mean, a user needs to call another action to cancel voice delegation or does it have a duration period?

- Is there any limit of delegators a user can have? I mean, the user A can be the delegatee of any number of users?

**Comment by n13** [comment]
Yes there needs to be a cancel function 

The user can either assign another trust delegate or cancel delegation any time 

It lasts forever although I think the trust delegate should also be able to cancel - if they don’t want to do it anymore. 

No limit on number of users
