### ISSUE TITLE
High, medium, and low thresholds

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#60]
## Spec

High, medium and low thresholds for quorum and majority (unity)

-> pp 46 constitution

While we are at it, also add a description to each setting

## Implementation

Add the following fields to config
- impact high/med/low name
- description

All existing entries have "high" impact

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
- Do we have to add a `description` field to the `config_table` from settings?
- Just to clarify, we have to add impact high/med/low as new parameters in `config_table`, right?
- To determine the proposal's impact, should we add the `impact` field in the `proposals` table? or is it outside this issue's scope?

**Comment by n13** [comment]
> Hello, I have some questions:
> 
> * Do we have to add a `description` field to the `config_table` from settings?

Yes.

> * Just to clarify, we have to add impact high/med/low as new parameters in `config_table`, right?

Yes.

We also need a migration strategy

Normally I would make 2 branches, branch 1 is migration branch and deploys the new table structure with a new name - e.g. config2, and has a migrate action that migrates all data from config -> config2

But in our case since we initialize all settings in the reset action anyway, we can just deploy a migrate action that clears all data.

Then in branch 2 has the new data structure

So in this case - migrate branch has action "migrate" which just deletes the table

feature branch has new data structure and all gets initialized in init

Question: Since many contracts depend on config_table - do we need to recompile and redeploy them all too?

> * To determine the proposal's impact, should we add the `impact` field in the `proposals` table? or is it outside this issue's scope?

No, we don't need to modify proposals contract - proposals can figure out the impact and therefore the required votes % from config - that's the idea. 

In a proposal a user votes on a settings parameter - we can get the impact from the config table in the settings contract.
