### ISSUE TITLE
Funding Fee and Referendum fee burning

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#61]
## Spec 

Props and referendums cost 5% of the requested amount but limited to 555 and 11,111 

Fee returned of referendum passes, burned if not

pp 47 of constitution

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
- I would like to clarify if I understood well. For props, we have to check if the stake is 5% of the prop quantity or if it is within the given limits (555, 11,111), if the stake meets one of those conditions then the prop is ready to be voted, is that correct? In case it is correct, I noticed referendums table doesn't have a quantity field, how should I determine the requested amount?

**Comment by n13** [comment]
@IanMendozaJaimes Correct referendums don't have amounts, so leave the fees there as they are.

Referendum will then keep fixed cost as it is, and have the burn / return policy - I think it already has that.

Thanks for noticing!

**Comment by n13** [comment]
Max was set to 1,111, changed to 11,111

**Comment by n13** [comment]
Done - needs to be deployed, waiting for App to update.
