### ISSUE TITLE
Challenges and Quests

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#80]
## Challenges and quests

Discuss today Aug 27

Anyone can create a challenge or quest with their own money - ie, an org can
Anyone can claim a challenge or quest - whether or not the claim is successful is determined by the creator of the challenge

A challenge or quest can be created by a proposal that is voted on, then the funds come from the normal proposal funds
A challenge or quest that was created by proposal needs to then be voted on when it is claimed?

We need to figure out how to do this. "Private" challenges and quests are straightforward. Maybe some evaluators can be chosen, and the evaluators get to evaluate whether or not a challgenge has been fulfilled, or which part of a quest has been fulfilled. 

A quest would consist of a series of challenges of which each must be agreed upon for a payout. 

## Spec

- [ ] Chalenges are one time contributions - same as a Seeds proposal
- [ ] Quests consist of multiple challenges, each one tied to rewards
- [ ] Maybe simply make proposals such that they have action steps that must be fileld - like quests really. There's a lot of overlap and we want one structure that can handle all these cases. 

## Options

We should make it so anyone can create a challenge and quest and finance it. 

We can also make challenge and quest proposals so the challenges and quests get funded from the same funds that fund proposals.

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
1. What would be the difference between a challenge and a normal proposal? is it that challenges belong to a quest?

2. Related to overlap, normal proposals could be considered as quests with just one challenge?

3. Related to the rewards, are they going to be fixed by some config parameter? or a new table is needed to store the corresponded  reward for a particular challenge?

4. By finance it, do you mean any user can stake to any challenge?

5. Do quests need to be financed as well? or they are considered financed if all their challenges are financed

6. Do challenges in a quest could have an order? I mean, the challenge 2 could not start if challenge 1 is not completed? or quests are an unordered collection of challenges?

7. Proposals are approved by a majority, quests need to voted as well or only their challenges?

8. By get funded by the same funds that fund proposals, you mean get funded by the different bank accounts?

**Comment by n13** [comment]
@IanMendozaJaimes I think we need to discuss this in the meeting, it's a lot less straightforward than I thought.

**Comment by n13** [comment]
Yes. Mainly the quests complications are from the process they follow 
- creating a quest 
- applying for a quest 
- approving an applicant to start on a quest 
- submitting a quest result (done) - needs better wording 
- accepting quest result - payout 

So there’s a lot of steps to go through on both sides 

Just mentioning that quests themselves are easy and most of the work seems to be related to managing how to pick up, finish, and verify a quest. And add a few abandon / fail / cancel cases to the mix (all the “no” branches in the above)
I think we can use the same contract and if we want to have slightly different rules we can make it more generic / flexible. But since the basic requirement is the same would be good to use the same contract. 

Hypha could just be making use of a seeds contract for quests ?!
Although... I think the main difference is that hypha can pay out in a variety of coins whereas seeds will only use Seeds at least to start with
But I’m happy if the funding sources and possible payouts are super flexible to accommodate hypha
An easy way would be to stake coins into the quest contract
Or maybe there can be a callback into an arbitrary contract. That contract can then check the quest contract to see if the quest was completed and verified and pay out whatever to the beneficiary. 

Not sure that’s really possible but ... it might be. It could be an open action anyone can call which only checks for quest completion and does the payout. And keeps track which have already been paid out.

**Comment by n13** [comment]
## Background - from Discord chat

> Definitely agree with that @rieki#0579 . Quests are an amazing tool to make the game itself regenerative and world-changer. As part of the design of the game of SEEDS, I had a go at designing 2 blockchain tables that I wanted to run past @nikolaus#6776 Heger. It won't be correct however, it gives us a starting point. The only piece of tech missing is a UI for creating quests that will be stored on the blockchain. Open for anyone to create a quest
@Alex Prate#3418 Like that or similar - ;) 

# User Stories
The features of the contract will be

"I create a quest (clean my garden)"
-> Create quest -> creator, amount, task description

"I apply for a quest -> I want to clean your garden"
-> Apply for quest -> applicant, quest ID, applicant description ("why I can do this, who I am... etc)

"I accept an applicant -> I choose you to clean my garden"
-> Assign quest -> creator, quest ID, applicant, completion date, or list of milestone dates with [start, milestone1, ms2, ms3... end]

"Accept quest -> I will clean your garden now"
-> Accept quest -> applicant, quest ID

"I have completed a milestone / the quest -e.g,  I have cleaned the front yard"
-> Complete quest -> quest ID, URL to documentation (proof, images, etc), description

"You have completed the quest, here is your bounty"
-> bounty -> quest ID, milestone -> pays out milestone award and potentially ends quest ->> payment

"I was happy with cleaning the garden"
-> rate quest -> applicant, quest ID -> applicant calls this to express how they feel about the quest ->> reputation change

" I was happy with the applicant"
-> rate applicant -> creator, applicant, quest ID -> creator calls this to express how they feel about the applicant ->> reputation change

## Timeouts
"I expire this quest -> I cleaned the garden myself now"
-> expire quest quest id

"I expire this applicant -> he's not accepting the quest"
-> expireappl: applicant, quest ID

"I cancel this applicant -> he accepted but is not doing the job, never showed up, showed up but left again, etc"
-> cancelappl: applicant, quest ID

"I retract my application, didn't hear back"
-> retractappl: applicant, quest ID

"I quit this quest, it's too hard, that garden is a mess"
-> quit applicant, quest ID

**Comment by juliolrmonteiro** [comment]
Idea: Have pre-funded quests, where the proposer pays for the quest payout upfront, so it need no voting, it becomes active at once.

The proposer can be an individual, an Organization, or a DHO (with voting), the funds get held in escrow.

After the quest is done, all the sponsors (or those who voted for it) have to vote if the quest is fulfilled

**Comment by juliolrmonteiro** [comment]
For the record here's the DHO version of the Quests specs:

https://github.com/hypha-dao/dho-web-client/issues/185

**Comment by juliolrmonteiro** [comment]
Here's the quest UI proposed by Joachim as the simple version (bounty) without Milestones or Team management.
![quest-ui](https://user-images.githubusercontent.com/5202858/102678523-e8611900-4187-11eb-9c0b-d90503e0f679.png)

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
- Challenges are the same as milestones right?
- Milestones should be added after the quest creation? or they should be added in the same action? is it possible to add, modify or delete milestones that are not completed or taken when the quest is assigned to someone?
- What would happen to the quest if for some reason the current milestone could not be completed?
- Let's say the user A completed the milestone, how does the user A will claim the funds? Currently I think the escrow contract needs to have a beneficiary, but as this is a bounty A will become the beneficiary only if A completes the milestone. Probably just transfer the total amount to the proposals contract and once the milestone is completed create a lock in the escrow contract?
- The quests can be created privately or can be voted. If they are private then they can be created immediately as soon as the quest creator stacks enough Seeds. If it is voted, then first it should be proposed through a proposal, but then once the proposal passes what the proposal should do, just give the money and trust the proposer will create the quest? or the proposal should be a special type of proposal that can create quests as soon as they pass?
- If the quest was voted, then all the voters have to vote again to give the quest as completed? do the voters have any other rights over the proposal?
- The milestones evaluation does not depend on onperiod right? To determine that a milestone is completed the quest creator can validate it whenever it wants right?
- Previously in this issue's discussion you mentioned that would be a good idea to have some sort of general structure that could handle proposals, quests and challenges, but I think with this new description quest/milestones are kind of different than proposals and they need to have their own tables, what do you think?

**Comment by juliolrmonteiro** [comment]
Here's some answers based on my understanding:

>  Challenges are the same as milestones right?

Challenges are like single step quests. The idea is to have a Quest object that may or may not have Milestones. If the Quest owner (responsible for the funds) finished the Quest without creating any Milestones, all the funds are transferred to him, and then it becomes like a regular Proposal.

> Milestones should be added after the quest creation? or they should be added in the same action? is it possible to add, modify or delete milestones that are not completed or taken when the quest is assigned to someone?

The quest owner (responsible for the funds) should be able to create/delete/modify not completed Milestones after creating the Quest, while the Quest itself is still not complete and there are still funds left in the quest payout pool. When they create a Milestone they select how much of the payout pool will be assigned.

> What would happen to the quest if for some reason the current milestone could not be completed?

Until the Milestone is completed it can be modified/deleted and the funds should return to the main Quest pool. Each milestone should have an assigned worker (assigned by the Quest owner).

> Let's say the user A completed the milestone, how does the user A will claim the funds? Currently I think the escrow contract needs to have a beneficiary, but as this is a bounty A will become the beneficiary only if A completes the milestone. Probably just transfer the total amount to the proposals contract and once the milestone is completed create a lock in the escrow contract?

The Milestone worker is the only one that can move it's status to "Complete", once the owner finished review, they move the status to "Done" and the payment is made to the worker for the funds allocated to that Milestone.

> The quests can be created privately or can be voted. If they are private then they can be created immediately as soon as the quest creator stacks enough Seeds. If it is voted, then first it should be proposed through a proposal, but then once the proposal passes what the proposal should do, just give the money and trust the proposer will create the quest? or the proposal should be a special type of proposal that can create quests as soon as they pass?

Private quests are funded by the creator (they become Quest owners) and are started immediately. Voted quests are special, once they are approved the owner of the proposal becomes the Quest owner (responsible for the the funds), then they have to create Milestones in order to pay people for working on the quest.

> If the quest was voted, then all the voters have to vote again to give the quest as completed? do the voters have any other rights over the proposal?

On voted Quests, as soon as the Quest or any of its Milestones becomes complete, a new quarter cycle voting round starts, so the original voters may have a chance to block/veto that funds transfer (1 vote per account, 100% unity, 0% quorum).

> The milestones evaluation does not depend on onperiod right? To determine that a milestone is completed the quest creator can validate it whenever it wants right?

For private quests, the Quest owner can take as long as they want to evaluate. For voted quests it's a voting round.

> Previously in this issue's discussion you mentioned that would be a good idea to have some sort of general structure that could handle proposals, quests and challenges, but I think with this new description quest/milestones are kind of different than proposals and they need to have their own tables, what do you think?

It's ok to use a new different table structure, but the way I see, Proposals can be generalized as Quests that have no Milestones. Up to you, they are different enough to justify new tables.

@n13 do you have anything else to add?

**Comment by juliolrmonteiro** [comment]
Proposed state machine for quest milestones:

![Quest-milestones2](https://user-images.githubusercontent.com/5202858/103175662-68534700-484a-11eb-9a8a-30244ec0bb5e.png)

**Comment by IanMendozaJaimes** [comment]
Hello, I have some more questions:
- Should I start using the hypha's documents?
- Which bank will be funding voted quests?

> On voted Quests, as soon as the Quest or any of its Milestones becomes complete, a new quarter cycle voting round starts, so the original voters may have a chance to block/veto that funds transfer (1 vote per account, 100% unity, 0% quorum).
- Sorry, I got confused, when you say a new quarter voting round starts, do you mean that each quest has its own voting period?  I thought voted quests could be evaluated (if there is a milestone to evaluate) each time `onperiod` from proposals is called, which would be a voting round, is that right?

**Comment by juliolrmonteiro** [comment]
Simplification: no team management

- There are the quest owners/validators and a quest assignee.
- The owner can be a private account (private quest) or a bank (voted quest), those who vote yes become 
- A quest is created with 0-N Milestones (and this can't be changed later)
- After the quest is approved, it becomes open for assignment (by individual or organization accounts)
- Once some account shows up for assignment, there is a voting from the quest owners, if approved, that account becomes the assignee.
- Once the Milestone/Quest is completed it enters the next quarter cycle `onperiod` voting
- Voters have 80% unity and 20% quorum as well
- If the Milestone/Quest is approved, the funds get transferred to the quest assignee
- If it's rejected it can be resubmitted later
- Any quest owner can send a quest suspension request, that is voted as well

**Comment by juliolrmonteiro** [comment]
Mimic the proposal contract to vote inside the new quest contract, but the voting power is still based on the proposal voting power.
We should use a new separate bank to fund quests, or maybe the quest contract as the bank.

**Comment by juliolrmonteiro** [comment]
After Eoslime is up, try to write tests using it
