### ISSUE TITLE
App tracking

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#81]
## Apps can call a special function with account / app that tracks app use

In organization contract:
- org can register an app (name, string longname)
- org contract track app (account, appname) - signed by account
- banapp(name) with contract rights - ban misbehaving apps

For now we can just track the number of app uses on chain.

We can rely on manual checking to see that the app dodn't cheat and just call trackapp without doing anything - it's only expected to be preloaded on existing actions, like votes, transfers, etc

But I think there's no way to verify that on chain, so we can rely on off chain checking for the time being, I think we'll only have Seeds Passport and Seeds Light Wallet for now anyway, we can test this system, and add more sophisticated tracking later.

It would be nice to track DAU rather than just actions too

**Comment by IanMendozaJaimes** [comment]
1. By App you mean Seeds Passport and Seeds Light Wallet?
2. Do we have to track the usage per user or per action maybe? 
3. When org registers an app, it means we have to create a new table to store the apps register by this org?, like: 
   app_table { 
       name app_name;
       string app_long_name;
       boolean is_banned;
       uint64_t  number_of_uses;
   } scoped by org
4. Does the number of app uses have to be stored in a table?
5. How could I track when a user uses the app?
6. In the documentation I saw DAU is the same as App points, but what are App points? I didn't see them in the documentation

**Comment by n13** [comment]
Thinking about DAU I think it can be done with a users table scoped by app and a counter - the counter increases when a user uses the app and the counter is reset every 24h, and when that happens the daily active users for the app are stored in another table with date and DAU also scoped by app

That's one possible solution - it avoids having to empty the tables all the time

**Comment by IanMendozaJaimes** [comment]
For DAU tracking, instead of 2 tables, we could use a single table with the following structure, what do you think?

dau_table {
  uint64_t id;
  name account;
  uint64_t date // day could be set up to be year-month-dayT00:00:00
  uint64_t number_app_uses;
} scoped by app

with this table structure we would create a new entry per user every day or update the entry if there is one, account and date would be secondary indices

**Comment by IanMendozaJaimes** [comment]
Hello I have another doubt:
- If org can register apps, who has to sign this actions, the contract itself or some member belonging to the organization?.

**Comment by n13** [comment]
Good question. Let’s make it the owners of the org for now ? 

Not any member. Only the owner.

**Comment by n13** [comment]
It should also cost Seeds. But I can add that later

**Comment by n13** [comment]
Done
