### ISSUE TITLE
Add Total transactions counter 

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#90]
### Option 1: Simply stop resetting total every week, use that

This is simple but somewhat hacky - we have incoming, outgoing and total - it's redundant

So rather than having to migrate data, we can just use total for all time total, and reset incoming and outgoing weekly

Problem: No nice way of restoring the old values. Which for the record we never kept track of - our counters were always supposed to reset weekly, only we didn't do it.

### Option 2 - keep track in history contract

- [ ] Add stats table in history contract - account name and total transactions - I don't want to redeploy the token contract

- account name
- incoming_tx, outgoing_tx
- timestamp time last updated

- [ ] add migration method that counts all existing tx and updates the number

- [ ] On new entry, update the number for bot

- [ ] change transactions check in makecitizen and makeresident in accounts contract to use that value, update the value first

**Comment by VasylMarchuk** [comment]
Maybe we could keep (and recalculate) `total_transactions`, `incoming_tx`, `outgoing_tx` and add new fields `weekly_total`, `weekly_incoming`, `weekly_outgoing` and reset the latter weekly instead of the former?

**Comment by n13** [comment]
Fixed the counter issue - app can make calls to scope and get the count of transactions with a normal HTTP call

```
REQUEST:
---------------------
POST /v1/chain/get_table_by_scope HTTP/1.0
Host: node.hypha.earth
content-length: 143
Accept: /
Connection: close

{
  "code": "histry.seeds",
  "table": "transactions",
  "lower_bound": "vasylmarchuk",
  "upper_bound": "",
  "limit": 1,
  "reverse": false
}
---------------------
{
  "rows": [{
      "code": "histry.seeds",
      "scope": "vasylmarchuk",
      "table": "transactions",
      "payer": "histry.seeds",
      "count": 4
    }
  ],
  "more": "vasylmarchuk"
}
```

**Comment by n13** [comment]
@VasylMarchuk closing this
