### ISSUE TITLE
Iterative Vote distribution

### ISSUE THREAD

**Issue by n13** [JoinSEEDS/seeds-smart-contracts#92]
So votes don't time out when there's too many users

https://app.asana.com/0/1156326769819664/1185437910782734/f

**Comment by IanMendozaJaimes** [comment]
Hello, I have some questions:
- By vote distribution should be iterative you mean to use batches in the method `update_voice_table`?
- To recalculate the CS points a few times a day is it ok to just put the action `updatecs` in the harvest contract to the scheduler?

**Comment by n13** [comment]
> Hello, I have some questions:
> 
> * By vote distribution should be iterative you mean to use batches in the method `update_voice_table`?

--> Yes, exactly


> * To recalculate the CS points a few times a day is it ok to just put the action `updatecs` in the harvest contract to the scheduler?

CS should already be updating every hour, they are already in the scheduler. If they're not it's a bug.

**Comment by n13** [comment]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/65412/90308725-33b9a100-dee2-11ea-9331-95a03b568bb5.png">


CS is updating - FYI .. caclcs calculates cs points, and rankcs is run after to rank CS.

The only issue in this is that planted is being calculated at the same time, that's not good. Need to wait for that to finish.
